### ISSUE TITLE
Error: Provider produced inconsistent final plan (aws_codebuild_project)

### ISSUE THREAD

**Issue by bkero** [terraform-providers/terraform-provider-aws#10615]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
Terraform v0.12.12
+ provider.aws v2.33.0
+ provider.cloudflare v1.18.1
+ provider.fastly v0.11.0
+ provider.null v2.1.2
+ provider.template v2.1.2

### Affected Resource(s)

* aws_codebuild_project

### Terraform Configuration Files

```hcl
resource "aws_codebuild_project" "kinesis_lambda" {
  name          = "ads-kinesis-lambda-transformation-codebuild"
  build_timeout = "60"
  service_role = "${aws_iam_role.codebuild_role.arn}"
  artifacts {
    type = "CODEPIPELINE"
  }
  environment {
    compute_type    = "BUILD_GENERAL1_SMALL"
    image           = "aws/codebuild/standard:1.0"
    type            = "LINUX_CONTAINER"
    privileged_mode = true
  }
  logs_config {
    cloudwatch_logs {
      group_name  = "${aws_cloudwatch_log_group.kinesis_lambda_codebuild.name}"
      stream_name = "codebuild_logs"
    }
  }
  source {
    type      = "CODEPIPELINE"
    buildspec = "${data.template_file.kinesis_lambda_buildspec.rendered}"
  }
  tags = "${merge(map("Name","Kinesis Lambda CodeBuild Project" ), var.codepipeline_tags, var.custom_tags)}"
}
```

data.template_file.kinesis_lambda_buildspec
```yaml
version: 0.2

env:
    parameter-store:
        LAMBDA_BUCKET: ${ssm_lambda_bucket_name}

phases:
  install:
    runtime-versions:
        nodejs: 10
    commands:
      - echo "Upgrade to latest awscli and yamllint"
  pre_build:
    commands:
      - echo Validation started on `date`
  build:
    commands:
      - echo Validation completed on `date`
artifacts:
  files:
    - deploy-kinesis-lambda-transformation.yaml
```
### Panic Output
```
Error: Provider produced inconsistent final plan

When expanding the plan for
module.kinesis_lambda.aws_codebuild_project.kinesis_lambda to include new
values learned so far during apply, provider "aws" produced an invalid new
value for .source: planned set element
cty.ObjectVal(map[string]cty.Value{"auth":cty.SetValEmpty(cty.Object(map[string]cty.Type{"resource":cty.String,
"type":cty.String})), "buildspec":cty.UnknownVal(cty.String),
"git_clone_depth":cty.NullVal(cty.Number),
"insecure_ssl":cty.NullVal(cty.Bool), "location":cty.StringVal(""),
"report_build_status":cty.NullVal(cty.Bool),
"type":cty.StringVal("CODEPIPELINE")}) does not correlate with any element in
actual.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.
```

### Expected Behavior
Terraform apply should apply completely

### Actual Behavior
Resources fail to apply with the panic error

### Steps to Reproduce

1. `terraform apply`
