### ISSUE TITLE
template_cloudinit_config causes EC2 instance boot failure. Does it work?

### ISSUE THREAD

**Issue by henrydobson** [terraform-providers/terraform-provider-aws#1148]
I am trying and failing to merge multiple sections of cloud-init config together with Terraform's template_cloudinit_config feature for an EC2 instance. I cannot get any multipart templates to work.

Imagine 4 templates (simplified here): 
```
# template 1 
hostname: ${hostname} 

# template 2 
users: 
  - name: "a" 
  - name: "b" 
  - name: "c" 

# template 3 
coreos: 
  units: 
    - name: ${service}.service 

# template 4 
coreos: 
  units: 
    - name: ${service2}.service 
```
If TF MIME encodes these with cloud-config headers... 
```
--MIMEBOUNDARY 
Content-Transfer-Encoding: 7bit 
Content-Type: text/cloud-config 
Mime-Version: 1.0 
```
I'm a little unsure about the correct merge type to use to achieve output like the following but there seems to be a greater issue that means multipart files aren't running correctly.
```
# output 
hostname: ${hostname} 
users: 
  - name: "a" 
  - name: "b" 
  - name: "c" 
coreos: 
  units: 
    - name: ${service}.service 
    - name: ${service2}.service
```
### Terraform Version
0.9.11

### Affected Resource(s)
Please list the resources as a list, for example:
- template_cloudinit_config
- aws_instance

### Terraform Configuration Files
```hcl
data "template_file" "coreos01_common" {
  template = "${file("data/cloud_config_common.tpl")}"

  vars {
    hostname = "coreos01"
  }
}

data "template_file" "coreos01_ssl" {
  template = "${file("data/cloud_config_write_files.tpl")}"

  vars {
    path = "/opt/ssl/ssl.pem"
    content = "${base64encode(file("data/ssl.pem"))}"
  }
}

data "template_file" "coreos01_config" {
  template = "${file("data/cloud_config_write_files.tpl")}"

  vars {
    path = "/opt/service/config.yaml"
    content = "${base64encode(file("data/config.yaml"))}"
  }
}

data "template_file" "coreos01_service" {
  template = "${file("data/cloud_config_coreos.tpl")}"

  vars {
    service = "redacted"
    ports = "redacted"
    volumes = "redacted"
  }
}

data "template_cloudinit_config" "coreos01_init" {
  gzip = true
  base64_encode = false

  part {
    content_type = "text/cloud-config"
    content      = "${data.template_file.coreos01_common.rendered}"
  }

  part {
    content_type = "text/cloud-config"
    content      = "${data.template_file.coreos01_ssl.rendered}"
    merge_type   = "dict(recurse_array)+list(append)"
  }

  part {
    content_type = "text/cloud-config"
    content      = "${data.template_file.coreos01_config.rendered}"
    merge_type   = "dict(recurse_array)+list(append)"
  }

  part {
    content_type = "text/cloud-config"
    content      = "${data.template_file.coreos01_service.rendered}"
    merge_type   = "dict(recurse_array)+list(append)"
  }

}

resource "aws_instance" "coreos01" {
  ami                         = "ami-a0ff1ed9"
  instance_type               = "t2.micro"
  user_data                   = "${data.template_cloudinit_config.coreos01_init.rendered}"
  key_name                    = "redacted"
  vpc_security_group_ids      = ["redacted"]
  subnet_id                   = "redacted"
  associate_public_ip_address = true

  root_block_device {
    volume_type   = "standard"
    volume_size   = "20"
  }
}
```

data/cloud_config_common.tpl
```
hostname: ${hostname}
# include one or more SSH public keys
ssh_authorized_keys:
  - ssh-rsa redacted
```

data/cloud_config_coreos.tpl
```
coreos:
  units:
    - name: ${service}.service
      command: start
      content: |
          redacted
```

data/cloud_config_write_files.tpl
```
write_files:
- path: "${path}"
  permissions: "0644"
  owner: "root"
  encoding: "base64"
  content: |
    ${content}
```

### Expected Behavior
Successful instance start and cloudinit apply.

### Actual Behavior
Instance restart loop. Container Linux Ignition fails to start. 

EC2 System Log Output
```
[    3.593810] systemd[1]: Started Generate new UUID for disk GPT dev/disk/by-diskuuid/00000000-0000-0000-0000-000000000001.[[0;32m  OK  [0m] Started Generate new UUID for disk …00000-0000-0000-0000-000000000001.

         Starting Ignition (disks)...



[[0;1;31mFAILED[0m] Failed to start Ignition (disks).

See 'systemctl status ignition-disks.service' for details.[    3.615001] 

[[0;1;33mDEPEND[0m] Dependency failed for Ignition (files).systemd[1]: Starting Ignition (disks)...

[    3.620503] ignition[382]: Ignition v0.14.0

[    3.622966] systemd[1]: ignition-disks.service: Main process exited, code=exited, status=1/FAILURE

[[0;1;33mDEPEND[0m] 

Dependency failed for Ignition (record completion).[    3.634872] systemd[1]: Failed to start Ignition (disks).

[    3.637689] ignition[382]: no config URL provided

[    3.640318] systemd[1]: Dependency failed for Ignition (files).

[    3.643963] systemd[1]: Dependency failed for Ignition (record completion).
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
-

### References
-
