### ISSUE TITLE
aws_cloudformation_stack resource consistently detects changes to yaml template terraform 0.12.20

### ISSUE THREAD

**Issue by marcincuber** [terraform-providers/terraform-provider-aws#11933]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
0.12.20
# aws provider version
2.47.0
```

### Affected Resource(s)

* aws_cloudformation_stack

### Terraform Configuration Files

Content of file `worker-node-spot-stack.yaml`

```yaml
Conditions:
  IsASGAutoAssignPublicIp: !Equals [ !Ref ASGAutoAssignPublicIp , "yes" ]
  IsASGMetricsEnabled: !Equals [ !Ref ASGMetricsEnabled , "yes" ]

Resources:

  NodeGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AutoScalingGroupName: !Ref NodeGroupName
      DesiredCapacity: !Ref NodeAutoScalingGroupDesiredCapacity
      MixedInstancesPolicy:
        InstancesDistribution:
          OnDemandAllocationStrategy: prioritized
          OnDemandBaseCapacity: !Ref OnDemandBaseCapacity
          OnDemandPercentageAboveBaseCapacity: !Ref OnDemandPercentageAboveBaseCapacity
          SpotAllocationStrategy: !Ref SpotAllocStrategy
        LaunchTemplate:
          LaunchTemplateSpecification:
            LaunchTemplateId: !Ref SpotLaunchTemplate
            Version: !GetAtt SpotLaunchTemplate.LatestVersionNumber
          Overrides:
            - InstanceType: !Select [0, !Split [ ",", !Ref InstanceTypesOverride ] ]
            - InstanceType: !Select [1, !Split [ ",", !Ref InstanceTypesOverride ] ]
            - InstanceType: !Select [2, !Split [ ",", !Ref InstanceTypesOverride ] ]
            - InstanceType: !Select [3, !Split [ ",", !Ref InstanceTypesOverride ] ]
            - InstanceType: !Select [4, !Split [ ",", !Ref InstanceTypesOverride ] ]
            - InstanceType: !Select [5, !Split [ ",", !Ref InstanceTypesOverride ] ]

      MinSize: !Ref NodeAutoScalingGroupMinSize
      MaxSize: !Ref NodeAutoScalingGroupMaxSize
      MetricsCollection:
      - Fn::If:
        - IsASGMetricsEnabled
        - 
          Granularity: 1Minute
          Metrics:
            - "GroupMinSize"
            - "GroupMaxSize"
            - "GroupDesiredCapacity"
            - "GroupInServiceInstances"
            - "GroupPendingInstances"
        - !Ref 'AWS::NoValue'
```

```hcl
resource "aws_cloudformation_stack" "spot_worker" {
  name         = "${local.name_prefix}-spot-worker-nodes-stack"
  capabilities = ["CAPABILITY_IAM"]
  ...
  ...
  template_body = file("worker-node-spot-stack.yaml")
}
```

### Debug Output
```
           -       MetricsCollection:
          +       MetricsCollection:
                  - Fn::If:
                    - IsASGMetricsEnabled
                    -
                      Granularity: 1Minute
          -           Metrics:
          +           Metrics:
                        - "GroupMinSize"
                        - "GroupMaxSize"
                        - "GroupDesiredCapacity"
                        - "GroupInServiceInstances"
                        - "GroupPendingInstances"
                    - !Ref 'AWS::NoValue'
```
```
Plan: 0 to add, 1 to change, 0 to destroy.
```
### Expected Behavior

I wouldn't expect anything to change.

### Actual Behavior

Changes to cloudformation template detected even though nothing has changed. So, changes are being detected every time I run terraform plan or apply.

### Steps to Reproduce

1. `terraform plan`
2. `terraform apply`

Any solutions to this problem?
