### ISSUE TITLE
Manage Route53 TXT record values as independent resources

### ISSUE THREAD

**Issue by beanaroo** [terraform-providers/terraform-provider-aws#12322]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

- Terraform can currently only manage entire DNS records
- Amazon Route53 does not permit multiple TXT records for a domain

This poses a problem when sharing a domain across states (accounts/environments/stages) for things like ACM (SSL) and SES (Email).

For example, AWS Workmail will create a TXT record for `_amazonses.acme.com.`

Terraforming an SES domain identity along with validation fails because the above record already exists. The same is true when adding any additional SES domain identity for the same domain in another region and/or account.

Since Amazon does not permit multiple TXT records for a domain, it would be ideal if Terraform could manage the values independently.

### New or Affected Resource(s)

* **data.aws_route53_txt_record** - provides a way to identify an external TXT record
* **aws_route53_txt_record_value** - a value to be added to the existing set of values

### Potential Terraform Configuration

```hcl

data "aws_route53_txt_record" "amazon-ses" {
  zone_id = "${aws_route53_zone.primary.zone_id}"
  name    = "_amazonses.acme.com."
}

resource "aws_route53_txt_record_value" "acme-ses-sydney" {
  record = "${data.aws_route53_txt_record.amazon-ses.id}"
  values = ["${aws_ses_domain_identity.acme-sydney.verification_token}"]
}

```

### Alternatives
If someone can provide alternative solutions to sharing a TXT record across states/accounts/regions/stages/environments, recommendations are welcome.

**Comment by jnewton03** [comment]
@beanaroo did you ever find a workaround or solution to this problem?  I'm having the same issue trying to implement SES across multiple accounts.

**Comment by beanaroo** [comment]
@jnewton03 Unfortunately no solution but a less than ideal workaround...

We've moved all SES and ACM resources into our Route53 module that's used by a single state. This now requires some double-handling when introducing/removing resources and introduced tight coupling between our environment states and the common resources account state that hosts Route53.

We'd still benefit from the above capability.


<details>
  <summary>Our configuration looks like this</summary>

```yaml
domains:

  acme:

    # Creates a hosted zone
    name: 'acme.com'
    provision: true
    delegated: false

    # Explicit records
    records:
      - name: foo.acme.com.
        type: A
        ttl: 3600
        value:
          - 333.101.123.99

    # SES identities in relevant accounts along with their aggregated verification records in the hosted zone account
    ses:
      workmail:
        txt: 'r/zsdfasdgxcvgbsdfgertasdfgsdfgsdfgs='
      notifications: true
      accounts:
        # Shared Stuff
        - account: '34562345236'
          regions: [us-east-1]
        # Dev
        - account: '45236345623'
          regions: [ap-southeast-2, eu-west-1]
        # Staging
        - account: '52365462334'
          regions: [ap-southeast-2, eu-west-1]
        # Production
        - account: '36546233452'
          regions: [ap-southeast-2, eu-west-1]

    # ACM Certificates in relevant accounts along with their aggregated verification records in the hosted zone account
    acm:
      alternatives:
        - '*.acme.com'
      accounts:
        # Dev
        - account: '45236345623'
          regions: [ap-southeast-2, us-east-1]
        # Staging
        - account: '52365462334'
          regions: [us-east-1]
        # Production
        - account: '36546233452'
          regions: [us-east-1]
```

</details>
