### ISSUE TITLE
Provider produced inconsistent final plan

### ISSUE THREAD

**Issue by pompbediener** [terraform-providers/terraform-provider-aws#12430]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
Terraform v0.12.3
+ provider.aws v2.53.0
+ provider.null v2.1.2
+ provider.template v2.1.2

### Affected Resource(s)

aws_cloudformation_stack.backup-vault

### Terraform Configuration Files
```hcl
resource "aws_cloudformation_stack" "backup-vault" {
  provider = "aws.central"

  name               = "${var.OTAP}backup-cfs-vault${var.region}"
  timeout_in_minutes = 120
  capabilities       = ["CAPABILITY_IAM"]


  parameters = {
    BackupVaultName  = "${var.BackupVaultName}"
    EncryptionKeyArn = "${var.EncryptionKeyArn}"
    Application = "${var.application}"
    OTAP        = "${var.OTAP}"
  }

  template_body = "${data.template_file.backup-vault.rendered}"

  tags = {
    Name               = "${var.OTAP}backup-cfs-vault${var.region}"
    "OTAP Environment" = "${var.OTAP}"
    Application        = "${var.application}"
  }
}
```
```yaml
---
AWSTemplateFormatVersion: '2010-09-09'
Description: BackupPlan
Parameters:
  Application:
    Default: SOMEAPPLICATION
    Type: String
  BackupVaultName:
    Type: String
  OTAP:
    Default: T
    Type: String
  EncryptionKeyArn:
    Type: String
Resources:
  BackupVault:
    Type: AWS::Backup::BackupVault
    Properties: 
      BackupVaultName: !Ref BackupVaultName
      EncryptionKeyArn: !Ref EncryptionKeyArn
      BackupVaultTags: {
        "Name": !Ref BackupVaultName,
        "Application": !Ref Application,
        "OTAP Environment": !Ref OTAP,
        "Backup-Vault" : "Generic-01"
        }
Outputs:
  BackupVaultArn:
    Description: BackupVaultArn
    Value: !GetAtt BackupVault.BackupVaultArn
  BackupVaultName:
    Description: BackupVaultName
    Value: !GetAtt BackupVault.BackupVaultName

```

### Debug Output

```
When expanding the plan for aws_cloudformation_stack.backup-rds to include new
values learned so far during apply, provider "aws" produced an invalid new
value for .parameters["DestinationBackupVaultArn"]: was
cty.StringVal("arn:aws:backup:eu-central-1:992155623828:backup-vault:bv-sdb-generic-01"),
but now
cty.StringVal("arn:aws:backup:eu-central-1:992155623828:backup-vault:bv-sdb-generic-01-ec1").

This is a bug in the provider, which should be reported in the provider's own
issue tracker.
```
### Expected Behavior

Terraform will handle the change within the resource ARN and updates its depending resources

### Actual Behavior

Depending resources are not updated.

### Steps to Reproduce

1. `terraform plan -out="planfile"`
2. `terraform apply "planfile"`
3. update resources within cloudformation stack
4. `terraform plan -out="planfile"`
5. `terraform apply "planfile"`
6. get error
