### ISSUE TITLE
Validate Examples Terraform Configurations via CI Testing

### ISSUE THREAD

**Issue by bflad** [terraform-providers/terraform-provider-aws#12861]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The Terraform AWS Provider codebase contains full Terraform configurations in the `examples` directory. Each of these directories should at a minimum have `terraform fmt` and `terraform validate` ran during pull requests for testing.

As a potential implementation, there are officially supported Terraform GitHub Actions available: https://github.com/hashicorp/terraform-github-actions/

For example (needs to be updated to handle per-directory checks):

```yaml
name: Examples Checks
on:
  pull_request:
    paths:
      - examples/**

env:
  tf_version: 'latest'
  tf_working_dir: '.'
jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: 'terraform fmt'
        uses: hashicorp/terraform-github-actions@v0.8.0
        with:
          tf_actions_version: ${{ env.tf_version }}
          tf_actions_subcommand: 'fmt'
          tf_actions_working_dir: ${{ env.tf_working_dir }}
          tf_actions_comment: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: 'terraform init'
        uses: hashicorp/terraform-github-actions@v0.8.0
        with:
          tf_actions_version: ${{ env.tf_version }}
          tf_actions_subcommand: 'init'
          tf_actions_working_dir: ${{ env.tf_working_dir }}
          tf_actions_comment: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: 'terraform validate'
        uses: hashicorp/terraform-github-actions@v0.8.0
        with:
          tf_actions_version: ${{ env.tf_version }}
          tf_actions_subcommand: 'validate'
          tf_actions_working_dir: ${{ env.tf_working_dir }}
          tf_actions_comment: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

### References

* Open examples pull requests, e.g. https://github.com/terraform-providers/terraform-provider-aws/pull/12833
