### ISSUE TITLE
New resource: Amazon Macie account association

### ISSUE THREAD

**Issue by ewbankkit** [terraform-providers/terraform-provider-aws#5202]
Add support for associating a specified AWS account with Amazon Macie as a member account.
Follows on from https://github.com/terraform-providers/terraform-provider-aws/issues/4992.
Requires https://github.com/terraform-providers/terraform-provider-aws/pull/5201.

**Comment by ewbankkit** [comment]
Fully automated acceptance tests will be difficult as there are [steps](https://docs.aws.amazon.com/macie/latest/userguide/macie-integration.html) that must be taken in the context of the member account to allow Macie to associate.

**Comment by bflad** [comment]
Looks like the CloudFormation template is really straightforward:

```yaml
Resources:
  AWSMacieServiceCustomerHandshakeRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: AWSMacieServiceCustomerHandshakeRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - "macie.amazonaws.com"
          Action:
          - sts:AssumeRole
          Condition:
            StringEquals:
              "sts:ExternalId": 
              - Ref : MasterAccount
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AmazonMacieHandshakeRole
```

So essentially the below (adding the service linked role for good measure):

```hcl
resource "aws_iam_service_linked_role" "AWSServiceRoleForAmazonMacie" {
  aws_service_name = "macie.amazonaws.com"
}

resource "aws_iam_role" "AWSMacieServiceCustomerHandshakeRole" {
  name = "AWSMacieServiceCustomerHandshakeRole"

  assume_role_policy = <<POLICY
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": "sts:AssumeRole",
      "Principal": {
        "Service": "macie.amazonaws.com"
      },
      "Condition": {
        "StringEquals": {
          "sts:ExternalId": "123456789012"
        }
      },
      "Effect": "Allow",
      "Sid": ""
    }
  ]
}
POLICY
}

resource "aws_iam_role_policy_attachment" "AWSMacieServiceCustomerHandshakeRole-AmazonMacieHandshakeRole" {
  policy_arn = "arn:aws:iam::aws:policy/service-role/AmazonMacieHandshakeRole"
  role       = "${aws_iam_role.AWSMacieServiceCustomerHandshakeRole.name}"
}
```
