### ISSUE TITLE
Expose naked aws_mq_broker hostname

### ISSUE THREAD

**Issue by izeau** [terraform-providers/terraform-provider-aws#5913]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently `aws_mq_broker` resources only expose their hostname via `console_url` and the `endpoints` list under the `instances` list:

```yml
aws_mq_broker.broker:
  instances:
    - console_url: 'https://<hostname>:8162'
      endpoints:
        - 'ssl://<hostname>:61617'
        - 'amqp+ssl://<hostname>:5671'
        - 'stomp+ssl://<hostname>:61614'
        - 'mqtt+ssl://<hostname>:8883'
        - 'wss://<hostname>:61619'
```

I'd like to access the hostname directly in order to create CNAME for it. At the time I’m using multiple `replace()` calls to remove the protocol and port but it's kind of a pain, plus the nested structure makes it quite difficult to access them when using an arbitrary number of instances.

Maybe a `hostname` attribute on the `instances` field would help.

### New or Affected Resource(s)

* aws_mq_broker
